\" Open-MX
\" Copyright © inria 2007-2009 (see AUTHORS file)
\"
\" The development of this software has been funded by Myricom, Inc.
\"
\" This program is free software; you can redistribute it and/or modify
\" it under the terms of the GNU General Public License as published by
\" the Free Software Foundation; either version 2 of the License, or (at
\" your option) any later version.
\"
\" This program is distributed in the hope that it will be useful, but
\" WITHOUT ANY WARRANTY; without even the implied warranty of
\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
\"
\" See the GNU General Public License in COPYING.GPL for more details.
\" General informations on the project

.TH OMX_HOSTNAME 1 "MARCH 2009"

.SH NAME
omx_hostname \- manipulate host names in the driver

.SH SYNOPSIS
.B omx_hostname [ options ]

.SH DESCRIPTION
.B omx_counters
change the hostname associated with a local interface
(the first interface by default),
or clears all known peer names.

.SH OPTIONS
.TP
.B -b <board number>
Use the interface given by
.B <board number>
instead of the first interface (number 0).

.TP
.B -n <hostname>
Set the hostname of the given local interface.
This option requires privileged access.

.TP
.B -c
Clear all known remote peer names in the driver table
to force their rediscovery.
This option requires privileged access.

.TP
.B -v
Display verbose messages.

.TP
.B -h
Display a brief help message.

.SH SEE ALSO
omx_info(1), omx_init_peers(1)

.SH AUTHOR
Brice Goglin
