\" Open-MX
\" Copyright © INRIA 2007-2009 (see AUTHORS file)
\"
\" The development of this software has been funded by Myricom, Inc.
\"
\" This program is free software; you can redistribute it and/or modify
\" it under the terms of the GNU General Public License as published by
\" the Free Software Foundation; either version 2 of the License, or (at
\" your option) any later version.
\"
\" This program is distributed in the hope that it will be useful, but
\" WITHOUT ANY WARRANTY; without even the implied warranty of
\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
\"
\" See the GNU General Public License in COPYING.GPL for more details.
\" General informations on the project

.TH OMX_ENDPOINT_INFO 1 "MARCH 2009"

.SH NAME
omx_endpoint_info \- display information about Open-MX endpoints

.SH SYNOPSIS
.B omx_endpoint_info [ options ]

.SH DESCRIPTION
.B omx_endpoint_info
displays information about the currently running
Open-MX endpoints.
It lists all open endpoint on the given interface
(all interfaces by default)
including information about the owner process.
The raw interface is also listed if a peer discovery
tool is running.

.SH OPTIONS
.TP
.B -a
Report all interfaces (default).

.TP
.B -b <board number>
Only report information for the interface given by
.B <board number>
instead of all interfaces.

.TP
.B -v
Display verbose messages.

.TP
.B -h
Display a brief help message.

.SH SEE ALSO
omx_info(1)

.SH AUTHOR
Brice Goglin
